name: passkey-auth
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
    paths:
      - 'examples/passkey-auth/**'
      - '.github/workflows/passkey-auth.yml'
      - 'pnpm-lock.yaml'
  pull_request:
    paths:
      - 'packages/passkey-auth/**'
      - '.github/workflows/passkey-auth.yml'
      - 'pnpm-lock.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm -r --filter passkey-auth run build
      - uses: fission-suite/publish-action@v1.2.7
        with:
          machine_key: ${{ secrets.FISSION_MACHINE_KEY }}
          workdir: 'examples/passkey-auth'
