name: Release
env:
  CI: true
  FORCE_COLOR: 1
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      paths_released: ${{ steps.release.outputs.paths_released }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          # needs to be personal token so release PRs can run workflows
          token: ${{ secrets.GH_TOKEN }}
          command: manifest
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json
          default-branch: main
          release-type: node
  npm:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/odd-passkeys') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/odd-preact')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm -r publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  docs:
    needs: release
    if: |
      contains(fromJson(needs.release.outputs.paths_released), 'packages/odd-passkeys') ||
      contains(fromJson(needs.release.outputs.paths_released), 'packages/odd-preact')
    uses: './.github/workflows/reusable-docs.yml'
